admin/urls.py
# Student Test System
# Copyright (C) 2020-2021 Andrey Shmaykhel <shmayhel.andrey@gmail.com>,
#                         Alexander Solovyov
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

'''
This module contains admin URLs
'''

from django.urls import path
from . import views

app_name = 'admin'

urlpatterns = [
    #TO ADD: admin/, admin/groups/<group_id> (name = group_detail)
    path('', views.MainView.as_view(), name='admin'),
    path('users/', views.UserListView.as_view(), name='user_list'),
    path('users/<int:user_id>/', views.user_details, name='user_detail'),
    path('groups/<uuid:pk>/', views.GroupDetailView.as_view(), name='group_detail'),
    path('groups/<uuid:pk>/update/', views.StudentGroupUpdateView.as_view(), name='update_group'),
    path('groups/', views.GroupListView.as_view(), name='group_list'),
    path('groups/create/', views.StudentGroupCreateView.as_view(), name='create_group_form')
]

studenttest/urls.py
# Student Test System
# Copyright (C) 2020-2021 Andrey Shmaykhel <shmayhel.andrey@gmail.com>,
#                         Alexander Solovyov
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""studenttest URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.urls import include, path

urlpatterns = [
    path('', include('auth_base.urls')),
    path('admin/', include('admin.urls')),
    path('study/', include('study_base.urls')),
]

study_base/urls.py
# Student Test System
# Copyright (C) 2020-2021 Andrey Shmaykhel <shmayhel.andrey@gmail.com>,
#                         Alexander Solovyov
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""
This module contains study urls.
"""

from django.urls import path

from . import views

app_name = 'study_base'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('teacher/', views.TeacherHomeView.as_view(), name='teacher_home'),
    path('teacher/edit_test/<uuid:test_id>/', views.edit_test, name='edit_test'),
    path('teacher/plan_test_modular/', views.PlanTestModularView.as_view(), name='plan_test_modular'),
    path('teacher/edit_test_modular/<uuid:pk>/', views.EditTestModularView.as_view(), name='edit_test_modular'),
    path('teacher/plan_test_manual/', views.PlanTestManualView.as_view(), name='plan_test_manual'),
    path('teacher/edit_test_manual/<uuid:pk>/', views.EditTestManualView.as_view(), name='edit_test_manual'),
    path('teacher/create_module/', views.CreateTestModuleView.as_view(), name='create_module'),
    path('teacher/edit_module/<uuid:pk>/', views.EditTestModuleView.as_view(), name='edit_module'),
    path('teacher/create_tasksinglechoice/', views.CreateTestTaskSingleChoiceView.as_view(), name='create_tasksinglechoice'),
    path('teacher/create_taskmultiplechoice/', views.CreateTestTaskMultipleChoiceView.as_view(), name='create_taskmultiplechoice'),
    path('teacher/create_tasktext/', views.CreateTestTaskTextView.as_view(), name='create_tasktext'),
    path('teacher/planned_test_results/<uuid:pk>/', views.PlannedTestDetailView.as_view(), name='planned_test_results'),
    path('teacher/group/<uuid:pk>/', views.GroupDetailView.as_view(), name='group_detail'),
    path('headteacher/', views.HeadTeacherHomeView.as_view(), name='headteacher_home'),
    path('headteacher/teacher/<int:pk>/', views.TeacherDetailView.as_view(), name='teacher_detail'),
    path('headteacher/group/<uuid:pk>/', views.HeadGroupDetailView.as_view(), name='group_detail_head'),
    path('headteacher/module/<uuid:pk>/', views.ModuleDetailView.as_view(), name='module_detail'),
    path('headteacher/task/<uuid:pk>/', views.TaskDetailView.as_view(), name='task_detail'),
    path('student/', views.StudentHomeView.as_view(), name='student_home'),
    path('student/take_test/<uuid:test_id>/', views.take_test, name='take_test'),
    path('student/take_test_task/<uuid:attempt_id>/<int:task_num>/', views.take_test_task, name='take_test_task'),
    path('student/attempt_results/<uuid:pk>/', views.TestAttemptResultsView.as_view(), name='attempt_results'),
    path('student/attempt_list/<uuid:pk>/', views.PlannedTestAttemptsView.as_view(), name='attempt_list')
]

study_base/models.py
# Student Test System
# Copyright (C) 2020-2021 Andrey Shmaykhel <shmayhel.andrey@gmail.com>,
#                         Alexander Solovyov
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""
This module contains essential study and test models
"""

import uuid

from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy
from django.utils import timezone


class StudentGroup(models.Model):
    """
    Group of students to test
    """
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        verbose_name=gettext_lazy('ID')
    )
    name = models.CharField(max_length=255, verbose_name=gettext_lazy('Name'))
    teacher = models.ForeignKey(
        get_user_model(),
        on_delete=models.PROTECT,
        verbose_name=gettext_lazy('Teacher'),
        related_name='group_teacher'
    )
    students = models.ManyToManyField(get_user_model(), related_name='group_students')

    def __str__(self):
        return self.name


class TestModule(models.Model):
    """
    Module of similar tasks.
    """
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        verbose_name=gettext_lazy('ID')
    )
    name = models.CharField(max_length=255, verbose_name=gettext_lazy('Name'))

    def __str__(self):
        return self.name


class TestTask(models.Model):
    """
    Abstract model for test task.
    """
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        verbose_name=gettext_lazy('ID')
    )
    task_description = models.TextField(verbose_name=gettext_lazy('Task description'))
    module = models.ForeignKey(
        TestModule,
        on_delete=models.CASCADE,
        verbose_name=gettext_lazy('Module')
    )

    def __str__(self):
        return self.task_description[:100]


class TestTaskSingleChoice(TestTask):
    """
    Simple task with single choice.
    """


class TestTaskMultipleChoice(TestTask):
    """
    Simple task with multiple choice.
    """


class TestTaskChoiceItem(models.Model):
    """
    Abstract model for choice item.
    """
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        verbose_name=gettext_lazy('ID')
    )
    text = models.CharField(max_length=255, verbose_name=gettext_lazy('Text'))
    is_right = models.BooleanField(verbose_name=gettext_lazy('Right'))



class TestTaskSingleChoiceItem(TestTaskChoiceItem):
    """
    Single choice item.
    """
    task = models.ForeignKey(
        TestTaskSingleChoice,
        on_delete=models.CASCADE,
        verbose_name=gettext_lazy('Task')
    )


class TestTaskMultipleChoiceItem(TestTaskChoiceItem):
    """
    Multiple choice item.
    """
    task = models.ForeignKey(
        TestTaskMultipleChoice,
        on_delete=models.CASCADE,
        verbose_name=gettext_lazy('Task')
    )


class TestTaskText(TestTask):
    """
    Task with text answer.
    """
    answer = models.CharField(max_length=255, verbose_name=gettext_lazy('Answer'))


class PlannedTest(models.Model):
    """
    A planned test abstract model.
    """
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        verbose_name=gettext_lazy('ID')
    )
    name = models.CharField(max_length=255, verbose_name=gettext_lazy('Name'))
    student_group = models.ForeignKey(
        StudentGroup,
        on_delete=models.PROTECT,
        verbose_name=gettext_lazy('Student group')
    )
    begin_date = models.DateTimeField(verbose_name=gettext_lazy('Begin date'))
    end_date = models.DateTimeField(verbose_name=gettext_lazy('End date'))

    def __str__(self):
        return self.name

    def is_active(self):
        """
        Returns if test is active now.
        """
        now = timezone.now()
        return (now >= self.begin_date) and (now < self.end_date)


class PlannedTestModular(PlannedTest):
    """
    Test with random tasks based on modules.
    """
    module = models.ForeignKey(
        TestModule,
        on_delete=models.PROTECT,
        verbose_name=gettext_lazy('Module')
    )
    task_count = models.PositiveSmallIntegerField(verbose_name=gettext_lazy('Task count'))


class PlannedTestManual(PlannedTest):
    """
    Test with manually selected tasks.
    """
    tasks = models.ManyToManyField(TestTask, verbose_name=gettext_lazy('Tasks'))


class TestAttempt(models.Model):
    """
    Test attempt abstract model.
    """
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        verbose_name=gettext_lazy('ID')
    )
    student = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name=gettext_lazy('Student'))
    start_date = models.DateTimeField(auto_now_add=True, verbose_name=gettext_lazy('Start date'))
    finish_date = models.DateTimeField(null=True, verbose_name=gettext_lazy('Finish date'))
    test = models.ForeignKey(
        PlannedTest,
        on_delete=models.PROTECT,
        verbose_name=gettext_lazy('Test')
    )
    tasks = models.ManyToManyField(
        TestTask,
        through='TestAttemptTask',
        through_fields=('attempt', 'task'),
        verbose_name=gettext_lazy('Tasks')
    )
    result = models.FloatField(null=True, verbose_name=gettext_lazy('Result'))

    def is_finished(self):
        """
        Returns if test attempt is finished.
        """
        if self.finish_date:
            return True
        return False

    def result_percent(self):
        """
        Returns the result in percent.
        """
        return "{:.1f}".format(self.result*100) + '%'


class TestAttemptTask(models.Model):
    """
    Model for linking TestAttempt with TestTask with answer storage.
    """
    attempt = models.ForeignKey(TestAttempt, on_delete=models.CASCADE, verbose_name=('Test attempt'))
    task = models.ForeignKey(TestTask, on_delete=models.CASCADE, verbose_name=gettext_lazy('Task'))
    answer = models.CharField(max_length=255, verbose_name=gettext_lazy('Answer'), null=True)

study_base/forms.py
# Student Test System
# Copyright (C) 2020-2021 Andrey Shmaykhel <shmayhel.andrey@gmail.com>,
#                         Alexander Solovyov
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""
This module contains study forms.
"""

from django import forms

from .models import PlannedTestManual, PlannedTestModular, TestModule, TestTaskMultipleChoice, TestTaskMultipleChoiceItem, TestTaskSingleChoice, TestTaskSingleChoiceItem, TestTaskText


class PlanTestModularForm(forms.ModelForm):
    """
    Form for planning a modular test.
    """
    class Meta:
        model = PlannedTestModular
        fields = ['name', 'student_group', 'begin_date', 'end_date', 'module', 'task_count']


class PlanTestManualForm(forms.ModelForm):
    """
    Form for planning a manual test.
    """
    class Meta:
        model = PlannedTestManual
        fields = ['name', 'student_group', 'begin_date', 'end_date', 'tasks']


class CreateTestModuleForm(forms.ModelForm):
    """
    Form for creating test modules.
    """
    class Meta:
        model = TestModule
        fields = ['name']


class CreateTestTaskSingleChoiceItemForm(forms.ModelForm):
    """
    Form for creating test single choice task item.
    """
    class Meta:
        model = TestTaskSingleChoiceItem
        fields = ['text', 'is_right']


class CreateTestTaskMultipleChoiceItemForm(forms.ModelForm):
    """
    Form for creating test multiple choice task item.
    """
    class Meta:
        model = TestTaskMultipleChoiceItem
        fields = ['text', 'is_right']


CreateTestTaskSingleChoiceItemFormSet = forms.formset_factory(CreateTestTaskSingleChoiceItemForm)


CreateTestTaskMultipleChoiceItemFormSet = forms.formset_factory(CreateTestTaskMultipleChoiceItemForm)


class CreateTestTaskSingleChoiceForm(forms.ModelForm):
    """
    Form for creating test single choice task.
    """
    class Meta:
        model = TestTaskSingleChoice
        fields = ['task_description', 'module']


class CreateTestTaskMultipleChoiceForm(forms.ModelForm):
    """
    Form for creating test multiple choice task.
    """
    class Meta:
        model = TestTaskMultipleChoice
        fields = ['task_description', 'module']


class CreateTestTaskTextForm(forms.ModelForm):
    """
    Form for creating test text task.
    """
    class Meta:
        model = TestTaskText
        fields = ['task_description', 'module', 'answer']


class TakeTestTaskSingleChoiceForm(forms.Form):
    """
    Form for taking test single choice task.
    """
    answer = forms.ChoiceField(widget=forms.RadioSelect())

    def __init__(self, *args, **kwargs):
        choices = kwargs.pop('choices', ())
        super().__init__(*args, **kwargs)
        self.fields['answer'].choices = choices


class TakeTestTaskMultipleChoiceForm(forms.Form):
    """
    Form for taking test multiple choice task.
    """
    answer = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple())

    def __init__(self, *args, **kwargs):
        choices = kwargs.pop('choices', ())
        super().__init__(*args, **kwargs)
        self.fields['answer'].choices = choices


class TakeTestTaskTextForm(forms.Form):
    """
    Form for taking test text task.
    """
    answer = forms.CharField(max_length=255)

study_base/templates/study_base/group_detail.html
{% extends "base.html" %}

{% block title %}
{{ studentgroup.name }}
{% endblock %}

{% block content %}
<div class="container">
	<h1 class="mt-3">
		{{studentgroup.name}}
	</h1>
	<p><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-circle mr-2" viewBox="0 0 16 16">
		<path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
		<path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
	  </svg>Преподаватель группы — {{studentgroup.teacher.first_name}} {{studentgroup.teacher.last_name}}</p>
	<table class="table">
		<thead class="thead-light">
			<tr>
				<th>Ученики группы</th>
			</tr>
		</thead>
		<tbody>
			{% for user in studentgroup.students.all %}
				<tr>
					<td>{{user.first_name}} {{user.last_name}}</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
	<table class="table">
		<thead class="thead-light">
			<tr>
				<th colspan="2">Тестирования</th>
			</tr>
		</thead>
		<tbody>
			{% for test in tests %}
				<tr>
					<td>{{ test }}</td>
					<td><a href="{% url 'study_base:planned_test_results' test.id %}" class="btn btn-primary">Результаты</a></td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
	<a class="btn btn-info" href="{% url 'study_base:teacher_home' %}" role="button">Домой</a>
</div>
{% endblock %}

study_base/templates/study_base/group_detail_head.html
{% extends "base.html" %}

{% block title %}
{{ studentgroup.name }}
{% endblock %}

{% block content %}
<div class="container">
	<h1 class="mt-3">
		{{studentgroup.name}}
	</h1>
	<p><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-circle mr-2" viewBox="0 0 16 16">
		<path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
		<path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
	  </svg>Преподаватель группы — <a href="{% url 'study_base:teacher_detail' studentgroup.teacher.id %}">{{studentgroup.teacher.first_name}} {{studentgroup.teacher.last_name}}</a></p>
	<table class="table">
		<thead class="thead-light">
			<tr>
				<th>Ученики группы</th>
			</tr>
		</thead>
		<tbody>
			{% for user in studentgroup.students.all %}
				<tr>
					<td>{{user.first_name}} {{user.last_name}}</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
	<table class="table">
		<thead class="thead-light">
			<tr>
				<th colspan="2">Тестирования</th>
			</tr>
		</thead>
		<tbody>
			{% for test in tests %}
				<tr>
					<td>{{ test }}</td>
					<td><a href="{% url 'study_base:planned_test_results' test.id %}" class="btn btn-primary">Результаты</a></td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
	<a class="btn btn-info" href="{% url 'study_base:headteacher_home' %}" role="button">Домой</a>
</div>
{% endblock %}

study_base/templates/study_base/headteacher_home.html
{% extends "base.html" %}

{% block title %}
Панель администратора учебного процесса
{% endblock %}

{% block content %}
    <h1 class="mt-3 mb-4">Панель администратора учебного процесса</h1>
    <div class="row">
        <div class="col">
            {% if studentgroup_list %}
            <table class="table">
                <thead class="thead-light">
                    <tr>
                        <th colspan="2">Группы</th>
                    </tr>
                </thead>
                <tbody>
                    {% for studentgroup in studentgroup_list %}
                    <tr>
                        <td>{{ studentgroup.name }}</td>
                        <td><a href="{% url 'study_base:group_detail_head' studentgroup.id %}" class="btn btn-primary">Подробнее</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% endif %}
        </div>
        <div class="col">
            {% if modules %}
            <table class="table">
                <thead class="thead-light">
                    <tr>
                        <th colspan="2">Учебные модули</th>
                    </tr>
                </thead>
                <tbody>
                    {% for module in modules %}
                    <tr>
                        <td>{{ module.name }}</td>
                        <td><a href="{% url 'study_base:module_detail' module.id %}" class="btn btn-primary">Подробнее</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% endif %}
        </div>
    </div>
{% endblock %}

study_base/templates/study_base/student_home.html
{% extends "base.html" %}

{% block title %}
Панель студента
{% endblock %}

{% block content %}
    <h1 class="mt-3">Панель студента</h1>
    <div class="row">
        <div class="col">
            {% if studentgroup_list %}
        <!--<h2 class="mt-2">Группы</h2>-->
        <table class="table">
            <thead class="thead-light">
                <tr>
                    <th>Группы</th>
                </tr>
            </thead>
            <tbody>
                {% for studentgroup in studentgroup_list %}
                <tr>
                    <td><p>{{ studentgroup.name }}</p></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}
        </div>
    <div class="col">
        {% if plannedtest_list %}
        <table class="table">
            <thead class="thead-light">
                <tr>
                    <th>Запланированные тестирования</th>
                    <th>Пройти</th>
                    <th>Результаты</th>
                </tr>
            </thead>
            <tbody>
                {% for plannedtest in plannedtest_list %}
                    <tr>
                        <td>{{ plannedtest }}</td>
                        <td><a href="{% url 'study_base:take_test' plannedtest.id %}" class="btn btn-primary {% if not plannedtest.is_active %}disabled{% endif %}">Пройти</a></td>
                        <td><a href="{% url 'study_base:attempt_list' plannedtest.id %}" class="btn btn-primary">Результаты</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
    </div>
{% endblock %}

study_base/templates/study_base/teacher_detail.html
{% extends "base.html" %}

{% block title %}
{{ object.name }}
{% endblock %}

{% block content %}
<div class="container">
	<h1 class="mt-3">
		{{object.username}}
	</h1>
	{% if studentgroup_list %}
	<table class="table">
		<thead class="thead-light">
			<tr>
				<th colspan="2">Группы</th>
			</tr>
		</thead>
		<tbody>
			{% for studentgroup in studentgroup_list %}
			<tr>
				<td>{{ studentgroup.name }}</td>
				<td><a href="{% url 'study_base:group_detail_head' studentgroup.id %}" class="btn btn-primary">Подробнее</a></td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	{% endif %}
</div>
{% endblock %}

study_base/templates/study_base/teacher_home.html
{% extends "base.html" %}

{% block title %}
Панель преподавателя
{% endblock %}

{% block content %}
    <h1 class="mt-3">Панель преподавателя</h1>
    <div class="row">
        <div class="col">
            {% if studentgroup_list %}
            <table class="table">
                <thead class="thead-light">
                    <tr>
                        <th colspan="2">Группы</th>
                    </tr>
                </thead>
                <tbody>
                    {% for studentgroup in studentgroup_list %}
                    <tr>
                        <td>{{ studentgroup.name }}</td>
                        <td><a href="{% url 'study_base:group_detail' studentgroup.id %}" class="btn btn-info">Подробнее</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% endif %}
        </div>
        <div class="col">
            <table class="table">
                <thead class="thead-light">
                    <tr>
                        <th>Запланированные тестирования</th>
                        <th>Редактировать</th>
                        <th>Результаты</th>
                    </tr>
                </thead>
                <tbody>
                    {% for plannedtest in plannedtest_list %}
                    <tr>
                        <td>{{ plannedtest }}</td>
                        <td><a class="btn btn-secondary" href="{% url 'study_base:edit_test' plannedtest.id %}">Редактировать тестирование</a></td>
                        <td><a class="btn btn-success" href="{% url 'study_base:planned_test_results' plannedtest.id %}">Результаты</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <div class="dropdown float-right">
                <button class="btn btn-primary dropdown-toggle" type="button" id="planTest" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Запланировать тестирование
                </button>
                <div class="dropdown-menu" aria-labelledby="planTest">
                    <a class="dropdown-item" href="{% url 'study_base:plan_test_modular' %}">Запланировать тестирование по модулю</a>
                    <a class="dropdown-item" href="{% url 'study_base:plan_test_manual' %}">Запланировать тестирование по выбранным заданиям</a>
                </div>
            </div>
        </div>
    </div>
    <hr>
    <h2>Добавить задания</h2>
    <div class="btn-group mt-1" role="group" aria-label="Basic example">
        <a class="btn btn-primary" href="{% url 'study_base:create_module' %}" style="border-radius: .25rem">Создать модуль</a>
        <div class="dropdown ml-3">
            <button class="btn btn-success dropdown-toggle" type="button" id="addTask" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Добавить задание
            </button>
            <div class="dropdown-menu" aria-labelledby="addTask">
              <a class="dropdown-item" href="{% url 'study_base:create_tasksinglechoice' %}">Задание с выбором одного варианта ответа</a>
              <a class="dropdown-item" href="{% url 'study_base:create_taskmultiplechoice' %}">Задание с выбором нескольких вариантов ответа</a>
              <a class="dropdown-item" href="{% url 'study_base:create_tasktext' %}">Задание с кратким ответом</a>
            </div>
        </div>
      </div>
    <!--
        <a class="btn btn-primary mx-2 my-2" href="{% url 'study_base:create_tasksinglechoice' %}">Создать задание с выбором одного варианта ответа</a>
    <a class="btn btn-primary mx-2 my-2" href="{% url 'study_base:create_taskmultiplechoice' %}">Создать задание с выбором нескольких вариантов ответа</a>
    <a class="btn btn-primary mx-2 my-2" href="{% url 'study_base:create_tasktext' %}">Создать задание с кратким ответом</a>
    -->
{% endblock %}